### ISSUE TITLE
INCLUSIONS recommended for CHECKLIST:

### ISSUE THREAD

**Issue by PoornimaSubramanian** [a11yproject/a11yproject.com#428]
# Headings
- [ ] Avoid use of implicit headings or long list of headings in a single web page
- [ ] Do not use links as headings
# Images
- [ ] Use ALT="" for Decorative images
- [ ] Do not use Background Images (using CSS) for clickable images
# Testing
- [ ] Test with High Contrast mode ON (using Settings -> Ease of Access Center/Accessibility -> Turn on High Contrast)

**Comment by jpdevries** [comment]
Interesting. I'd like to read up more on 
> Do not use links as headings

Any suggested resources?

**Comment by joe-watkins** [comment]
@PoornimaSubramanian Thanks for the suggestions :) Here are my thoughts regarding your contribution:

**Headings**: The two suggestions you provide are 'generally' covered in the existing Document Outline section. "Use semantic headings and structure"

**Images:** : These are also covered in the Images section: "Use appropriate alt text" (Just noticed broken link there)

**Testing:**: This is a good one :).. but the directions for turning high contrast mode look to be specific to an app or operating system that may be different for some users.  I suggest making a PR for adding that -- maybe a link to a meaty article on the topic?

The checklist aims to be fairly broad while succinct .. we could get 'into the weeds' on it very easily with too many specific techniques.

**Comment by PoornimaSubramanian** [comment]
@joe-watkins Thanks for your reply 

Unfortunately, I couldn't find an article that covers High Contrast setting on different platforms. However, I documented the setting rules in popular platforms such as Windows OS, Mac OS and Chrome browser and attached here. Can you see if this could fit in nicely? 

Thanks,

[How to turn High Contrast mode ON.docx](https://github.com/a11yproject/a11yproject.com/files/374579/How.to.turn.High.Contrast.mode.ON.docx)

**Comment by joe-watkins** [comment]
@PoornimaSubramanian Sorry for the delay! That document is a great resource and would make a nice How-to article.  Here is [documentation on contributing articles](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#writing-articles).

Would you like to create a Gist and start a new issue when you have come up with something?

**Comment by svinkle** [comment]
@PoornimaSubramanian, any updates on the status of the article?

**Comment by ValorNaram** [comment]
Anything new here? Would like to add Linux/Ubuntu to list/how-to

**Comment by ericwbailey** [comment]
Closing this issue for inactivity, thank you to everyone for their contributions. Please feel free to re-open the issue if you would like to see the article published.
