### ISSUE TITLE
Checklist enhancements 

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#788]
See: https://github.com/a11yproject/a11yproject.com/pull/779#issuecomment-491527673

- [ ] Consider adding a dos and don'ts section to each checklist item.
- [ ] Consider adding a "further reading" section to each checklist item.
- [ ] Consider referencing each checklist item in a longer, more detailed post explaining why it's important.
- [ ] Provide a toggle to expand every item in checklist section/all checklist items on the page.

**Comment by ericwbailey** [comment]
See also: https://github.com/a11yproject/a11yproject.com/issues/942
