### ISSUE TITLE
Add checkboxes to checklist items

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#942]
Currently the site has no mechanism to let a user check off something in the checklist to mark it as reviewed. 

We should add the ability for someone to check each item on [the Checklist page](https://a11yproject.com/checklist/) off to indicate completion.

- [ ] Incorporate a checkbox pattern
- [ ] Make sure it does not have nested interactive control issues, especially with screen readers/voice control
- [ ] Use localstorage to persist checked/unchecked state between sessions

**Comment by SaptakS** [comment]
If no one is looking into this, I would love to work on this.

**Comment by ericwbailey** [comment]
@SaptakS Yeah! Same deal as #940?

**Comment by SaptakS** [comment]
Works!

**Comment by ericwbailey** [comment]
See also: https://github.com/a11yproject/a11yproject.com/issues/788
